### ISSUE TITLE
Does not support AMD plugins.

### ISSUE THREAD

**Issue by treasonx** [RaveJS/rave#35]
I ran into an issue while playing around with rave. When using the AMD moduleType it seems to be confused about how AMD plugins work. Actually not confused, it just doesn't use them

When I try to use my test plugin:

``` javascript
define(function(require, exports) {
  var thinger = require('plugin!somestuff');
});
```

I get a 404 for.

```
http://localhost:3474/plugin!somestuff.js 404 (Not Found) 
```

**Comment by unscriptable** [comment]
Heh, I believe you've uncovered a documentation issue, @treasonx!  

AMD plugins are supported, but only via rave extensions (due to limitations in the ES6 specs).  [Here](http://bower.io/search/?q=rave-curl) are some rave extensions for curl plugins.  

It's quite easy to create your own, actually.   Take a peek at those extensions and then look at this [helper package](https://github.com/unscriptable/rave-amd-plugins).

Which plugin are you using?

**Comment by treasonx** [comment]
Playing with Dojo and Rave from within an atom-shell. :) I don't always try new things, but when I do I try them all at once :)   

I think I understand what I need to do. 

Thanks!

**Comment by unscriptable** [comment]
lol.

Interested in creating a rave-dojo integration package? :)

I think @phated had looked into creating a rave-dojo integration project briefly.  I imagine he got distracted by the million other projects he's working on.  Just pinging him to see if he has any pointers or ideas.

**Comment by treasonx** [comment]
I was planning to create the package as I went along. If there is an existing package I would happily use that.

**Comment by unscriptable** [comment]
There's no existing package, afaik.  I'll gladly help in any way I can.

**Comment by unscriptable** [comment]
Closing this in favor of #36.

**Comment by phated** [comment]
I had a bunch of problems with dojo/has plugin and was never able to track down the root problem.
