### ISSUE TITLE
Base url option?

### ISSUE THREAD

**Issue by Bitaru** [RaveJS/rave#69]
Hi there!
I just started new php project with Rave, and caught that BaseUrl is `location.protocol + '//' + location.host + location.pathname`, i think most projects use fixed path for assets so may be better to use '/' or load baseUrl from meta?

**Comment by unscriptable** [comment]
Hi @Bitaru!

Thanks for posting this. Help me understand your use case. Does either of these describe the problem you have or foresee?
1. You have a multi-page app and the html documents may not all be in the same directory. The baseUrl would have to be different for each page. 
2. You have css, templates, and images in directories that are peers (or higher) to your JavaScript modules. You cannot access these from your JavaScript modules since rave doesn't let you access modules or assets above the module root (typically where you have the package.json or bower.json). 

-- john

**Comment by chrylis** [comment]
I'm not yet using Rave (still under consideration for the SPA version of our site; doing the sections that need progressive enhancement now), but I can say that scenario 1 would apply to me.

**Comment by Bitaru** [comment]
Hi John!

First point exactly match for me - project have 3 locales and bases(/en/, /de/, /ru/).
When rave start loading libs it drops 404 for packages, coz there is no folder /ru/ in project - `GET http://more.dev/ru/bower_components/backbone/backbone.js 404 (Not Found)`
Also, i think, baseUrl from meta in `init` function will be great solution for scripts storage at cdn.

**Comment by unscriptable** [comment]
Anybody interested in tackling this one?
